language: node_js
node_js:
  - 12
    
import:
    - source: flash-global/travis:js/common.yml@master
      mode: deep_merge_prepend
    - source: publish_npm.ymll@master
      mode: deep_merge_prepend
