language: node_js
node_js:
  - 12

before_script:
- npm install -g --unsafe-perm node-red
- cd sample && npm install && cd ..
- npm run start &
    
import:
    - source: flash-global/travis:js/common.yml@master
      mode: deep_merge_prepend
    - source: publish_npm.ymll@master
      mode: deep_merge_prepend
